tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y \
        libatk-1.0-0 \
        libatk-bridge2.0-0 \
        libcups2 \
        libdbus-1-3 \
        libgdk-pixbuf2.0-0 \
        libnspr4 \
        libnss3 \
        libx11-xcb1 \
        libxcomposite1 \
        libxdamage1 \
        libxrandr2 \
        libxss1 \
        libxtst6 \
        fonts-liberation \
        ca-certificates \
        wget \
        xdg-utils
      npm install
  - command: npm start
